### ISSUE TITLE
There's something wrong about the hands part and feet part.

### ISSUE THREAD

**Issue by yanhn** [kuboshizuma/UVTextureConverter#16]
Found some bad texture in feet part and hands part. Is there any plan to optimize them?

**Comment by kuboshizuma** [comment]
[This notebook](https://github.com/kuboshizuma/UVTextureConverter/blob/master/notebook/convert_texture_between_normal_and_altas.ipynb) shows examples, but each conversion seems to work for me.
In any case, I'm afraid that I can't think of any further optimizations, so I have no plans to update.

**Comment by yanhn** [comment]
I tried every step as the [notebook](https://github.com/kuboshizuma/UVTextureConverter/blob/master/notebook/convert_texture_between_normal_and_altas.ipynb) illustrated. I use the **Normal2Atlas** function to transfer this normal image 
![normal](https://user-images.githubusercontent.com/12744658/113824096-f3c96600-97b1-11eb-9dfe-e547f76b7284.jpg)
But got the result as shown below:
![Screenshot from 2021-04-07 15-00-42](https://user-images.githubusercontent.com/12744658/113824229-1c516000-97b2-11eb-97ea-d867907752ea.png)
You can find out the **hands and feet parts are misaligned**. That is the problem I mentioned. Could you please help solve this issue?
