### ISSUE TITLE
About Atlas2Normal conversion

### ISSUE THREAD

**Issue by AndrewChiyz** [kuboshizuma/UVTextureConverter#17]
Thanks for your code!

I have a few questions about the function to convert atlas texture to normal texture. 

1) There are three extra data files that need to be loaded in advance, including `config/UV_Processed.mat`, `config/normal_faces.pickle`, and `config/normal.pickle`. What are these files, and what kinds of data these files contain, respectively? 

2) If the input size of the atlas texture and mask is `[24, part_size, part_size, 3]` and `[24, part_size, part_size]`, respectively, and the output normal texture size is, say `512x512`, thus, the `Atlas2Normal` function is actually trying to convert the part-based UV coordinates (defined in SMPL model)  into a full-body version of UV coordinates. Is that correct? If so, how to get such correspondence between part-based UV coordinates and the full-body version of UV coordinates? Is there any mapping functions or index to find where the location should be in the outputted normal textures?

3) I have noticed that, in the initialization function of `Atlas2Norm`, the function tries to load another data file, namely, `mapping_relations/atlas2normal_{atlas_size}_{normal_size}.pickle`, which has been calculated when performing the first time of atlas2normal texture conversion. Does it mean the mapping function from atlas texture with `atlas_size` to normal texture with `normal_size` is actually fixed?

P.S. I have got some hints about the `UV_Processed.mat` data file from https://github.com/facebookresearch/DensePose/issues/146#issuecomment-464710963. But still do not know the data stored in the other extra files?  Would you please help me to understand the whole process, and how to use these extra data to perform Atlas2Normal conversion? 

Thanks a lot! :)

**Comment by yanhn** [comment]
UV_Processed.mat is a matlab file that contains the densepose information(UVs, faces).
This tool is used to convert SMPL texture(normal) into densepose texture(atlas) and the other way.
So it should get the uv-verts mapping relationship for both smpl and densepose, which should load the UV_Processed.mat file.
For the usage part, you should refer to the [notebook](https://github.com/kuboshizuma/UVTextureConverter/blob/master/notebook/convert_texture_between_normal_and_altas.ipynb).

**Comment by AndrewChiyz** [comment]
Thanks for your reply @yanhn! 

I have already go through the notebook and performed both directions of conversions. What confused me are the calculation and the theory behind these conversions. I could understand what are the goals of these conversion functions and how to use this code, but I would like to dive into these conversions and figure out how the codes do such conversions.  

It seems we have to load some extra data files, or some pre-defined mapping functions or parameters to achieve such conversions. What kind of information do these data files record and How does this data work, respectively? Could you please provide more details on those data or some links to help me figure that out? 

Thanks! :)

**Comment by kuboshizuma** [comment]
@AndrewChiyz 

Thank you for your questions.

> 1. There are three extra data files that need to be loaded in advance, including config/UV_Processed.mat, config/normal_faces.pickle, and config/normal.pickle. What are these files, and what kinds of data these files contain, respectively?

UVTextureConverter goes through `SMPL model` to convert `atlas texture` and `normal texture`. Therefore

- the relationship between `atlas texture` and `SMPL model`
- the relationship between `SMPL model` and `normal texture`

are required respectively. Each file has the following information.

- `UV_Processed.mat`: the relationship between `atlas texture` and `SMPL model`
- `normal_faces.pickle` and `normal.pickle`: the relationship between `SMPL model` and `normal texture`

In addition, `normal_faces.pickle` represents the relationship between points and faces, and `normal.pickle` represents the coordinates of points. These are prepared using blender.

> 2. If the input size of the atlas texture and mask is [24, part_size, part_size, 3] and [24, part_size, part_size], respectively, and the output normal texture size is, say 512x512, thus, the Atlas2Normal function is actually trying to convert the part-based UV coordinates (defined in SMPL model) into a full-body version of UV coordinates. Is that correct? If so, how to get such correspondence between part-based UV coordinates and the full-body version of UV coordinates? Is there any mapping functions or index to find where the location should be in the outputted normal textures?

Yes. When the conversion is performed, the relationship between the textures, which is the answer above, is used. In addition,　techniques such as the transformation of the barycentric coordinate system is used to transform the surface.

> I have noticed that, in the initialization function of Atlas2Norm, the function tries to load another data file, namely, mapping_relations/atlas2normal_{atlas_size}_{normal_size}.pickle, which has been calculated when performing the first time of atlas2normal texture conversion. Does it mean the mapping function from atlas texture with atlas_size to normal texture with normal_size is actually fixed?

The size is not limited, but a conversion with new sizes requires new calculations and is time consuming.

**Comment by AndrewChiyz** [comment]
Thanks a lot for the detailed reply! :)
