### ISSUE TITLE
How to get IUV ?

### ISSUE THREAD

**Issue by puechc** [kuboshizuma/UVTextureConverter#19]
Hello, the results are impressive and I would like to try create_uv_texture_from_image_by_using_densepose.ipynb with other images, but how to get the corresponding IUV.png?
Thanks in advance for your answer

**Comment by VVingerfly** [comment]
You can get IUV using [DensePose in Detectron2](https://github.com/facebookresearch/detectron2/tree/master/projects/DensePose)

**Comment by git-hamza** [comment]
Can you be more specific on how to generate this exact png file iuv from the pickle file

**Comment by kuboshizuma** [comment]
Sorry for my late reply. 
I used [facebookresearch/DensePose](https://github.com/facebookresearch/DensePose) repository  to get the IUV file. Especially [DensePose/GETTING_STARTED.md](https://github.com/facebookresearch/DensePose/blob/main/GETTING_STARTED.md) of the repository is helpful.
