### ISSUE TITLE
How to reduce unmapped pixels?

### ISSUE THREAD

**Issue by xhuan8** [kuboshizuma/UVTextureConverter#21]
The generated texture contains many unmapped pixels, is there any way to deal with these pixels?
I'm not sure it's dense pose problem or resolution problem.
![view_1](https://user-images.githubusercontent.com/53556761/142828569-df310db2-1fde-4785-844f-0f91a96232d2.png)

**Comment by kuboshizuma** [comment]
@xhuan8 
Could you tell me the details? I'd like you to share the following information.

- Atlas texture before conversion
- Size before and after conversion (atlas texture (default 200) and normal texture (default 512))

**Comment by xhuan8** [comment]
Thanks for your replay.

Atlas texture before conversion looks similar to the above image
Use the default size (200 for atlas and 512 for normal texture)

I solved this problem by resize the input image from 512 * 512 to 2048 * 2048.

there are some problems for dense pose, such as mirrored image and collapsed body, I'm testing the CSE approach.
![view_2](https://user-images.githubusercontent.com/53556761/146677011-1429168d-4466-4012-a02e-fb4c9d689495.png)
![view_1](https://user-images.githubusercontent.com/53556761/146677042-13769bd1-e01d-45a4-b2be-7ba19e120206.png)

**Comment by kuboshizuma** [comment]
@xhuan8 I'm glad to hear that it has been solved!
Thank you for sharing your information!
