### ISSUE TITLE
Is there a way to generate texture from image to smpl 10 parts style UV map?

### ISSUE THREAD

**Issue by wine3603** [kuboshizuma/UVTextureConverter#3]
こんにちは, kuboshizuma-sama,
Thanks for your nice work!
It's really wonderful and cool!
I noticed that your developed API can convert image to densepose 24 parts texture UV map, and then do atlas2normal translate to 10 parts UV map style.
I would like to ask if there is a function that can convert image to 10 part UV texture directly since I found the 2-step conversion consumes too much time( atlas2normal runs about 20 sec in my case).

**Comment by kuboshizuma** [comment]
@wine3603 
Thank you for your interest of my work!
Sorry for my late reply. It may have already been solved, but I'll answer below.

> I noticed that your developed API can convert image to densepose 24 parts texture UV map, and then do atlas2normal translate to 10 parts UV map style.

“10 parts UV map style” may be “normal texture” in my words. If so, yes.

> I would like to ask if there is a function that can convert image to 10 part UV texture directly since I found the 2-step conversion consumes too much time( atlas2normal runs about 20 sec in my case).

The process of converting the output of DensePose into an atlas texture is not a heavy process as it just associates an image with the output of DensePose. So I don't think the issue you pointed to will significantly improve speed.

It's strange that it takes 20 seconds. If the image size specified in the sample, my environment (macbook) takes less than a second to process.

Perhaps you are mapping with an image size different from the sample image. In this case, it takes time to calculate the mapping relationship only for the first processing. The calculation result will be stored in the `UVTextureConverter/UVTextureConverter/mapping_relations` folder. After that I think it will work faster.
