### ISSUE TITLE
Is it possible to extract textures directly from the iuv array rather than using IUV.png?

### ISSUE THREAD

**Issue by mithunlal** [kuboshizuma/UVTextureConverter#7]

**Comment by kuboshizuma** [comment]
Yes. This library supports a numpy array as well as a image path (IUV.png). ([Code](https://github.com/kuboshizuma/UVTextureConverter/blob/master/UVTextureConverter/UVConverter.py#L139-L150))
If you have additional questions, please open a new issue.
